<?php

return [
    /* ------------------------------------------------------------------------------------------------
     |  Module Namespace
     | ------------------------------------------------------------------------------------------------
     |  Default module namespace.
     */
    'namespace' => 'Arcanedev',

    /* ------------------------------------------------------------------------------------------------
     |  Module Stubs
     | ------------------------------------------------------------------------------------------------
     | Default module stubs.
     */
    'stubs' => [
        'enabled' => false,

        'path'    => base_path('/vendor/arcanedev/workbench/stubs'),

        'files'   => [
            'start'             => 'start.php',
            'routes'            => 'start/routes.php',
            'json'              => 'module.json',
            'views/index'       => 'resources/views/index.blade.php',
            'views/master'      => 'resources/views/layouts/master.blade.php',
            'scaffold/config'   => 'config/config.php',
            'composer'          => 'composer.json',
        ],

        'replacements' => [
            'start'             => ['LOWER_NAME'],
            'routes'            => ['LOWER_NAME', 'STUDLY_NAME', 'MODULE_NAMESPACE'],
            'json'              => ['LOWER_NAME', 'STUDLY_NAME', 'MODULE_NAMESPACE'],
            'views/index'       => ['LOWER_NAME'],
            'views/master'      => ['STUDLY_NAME'],
            'scaffold/config'   => ['STUDLY_NAME'],
            'composer'          => [
                'LOWER_NAME',
                'STUDLY_NAME',
                'VENDOR',
                'AUTHOR_NAME',
                'AUTHOR_EMAIL',
                'MODULE_NAMESPACE',
            ],
        ],
    ],

    'paths' => [
        /* ------------------------------------------------------------------------------------------------
         |  Modules path
         | ------------------------------------------------------------------------------------------------
         | This path used for save the generated module. This path also will added automatically
         | to list of scanned folders.
         */
        'modules'   => base_path('modules'),

        /* ------------------------------------------------------------------------------------------------
         |  Modules assets path
         | ------------------------------------------------------------------------------------------------
         | Here you may update the modules assets path.
         */
        'assets'    => public_path('modules'),

        /* ------------------------------------------------------------------------------------------------
         |  The migrations path
         | ------------------------------------------------------------------------------------------------
         | Where you run 'module:publish-migration' command, where do you publish the
         | the migration files?
         */
        'migration' => base_path('database/migrations'),

        /* ------------------------------------------------------------------------------------------------
         |  Generator path
         | ------------------------------------------------------------------------------------------------
         | Here you may update the modules generator path.
         */
        'generator' => [
            'config'        => 'config',
            'command'       => 'src/Commands',
            'migration'     => 'src/Database/Migrations',
            'seeder'        => 'src/Database/Seeders',
            'controller'    => 'src/Http/Controllers',
            'filter'        => 'src/Http/Middleware',
            'request'       => 'src/Http/Requests',
            'model'         => 'src/Models',
            'repository'    => 'src/Repositories',
            'provider'      => 'src/Providers',
            'assets'        => 'resources/assets',
            'lang'          => 'resources/lang',
            'views'         => 'resources/views',
            'test'          => 'tests',
        ],
    ],

    /* ------------------------------------------------------------------------------------------------
     |  Scan Path
     | ------------------------------------------------------------------------------------------------
     | Here you define which folder will be scanned. By default will scan vendor
     | directory. This is useful if you host the package in packagist website.
     */
    'scan' => [
        'enabled'   => false,
        'paths'     => [
            base_path('vendor/*/*'),
        ],
    ],

    /* ------------------------------------------------------------------------------------------------
     |  Composer File Template
     | ------------------------------------------------------------------------------------------------
     | Here is the config for composer.json file, generated by this package
     | in every module since version >= 1.2.0.
     */
    'composer' => [
        'vendor' => 'arcanedev',
        'author' => [
            'name'  => 'ARCANEDEV',
            'email' => 'arcanedev.maroc@gmail.com',
        ],
    ],

    /* ------------------------------------------------------------------------------------------------
     |  Caching
     | ------------------------------------------------------------------------------------------------
     | Here is the config for setting up caching feature.
     */
    'cache' => [
        'enabled'   => false,
        'key'       => 'arcanedev-modules',
        'lifetime'  => 60,
    ],
];
